workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - google_play   
      vars:
        JAVA_VERSION: "11"
    scripts:
      - echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
      - echo "storePassword=$CM_KEYSTORE_PASSWORD" > /tmp/key.properties
      - echo "keyPassword=$CM_KEY_PASSWORD" >> /tmp/key.properties
      - echo "keyAlias=$CM_KEY_ALIAS" >> /tmp/key.properties
      - echo "storeFile=/tmp/keystore.jks" >> /tmp/key.properties
      - flutter clean
      - flutter pub get
      - flutter build apk --release --flavor prod --target-platform android-arm,android-arm64,android-x64
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - amabeyonce0@gmail.com
